spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/delta

server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

gateway:
  routes:
    eventapp: http://localhost:8091/
    smallservice: http://localhost:8092/