spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: smallservice
          uri: http://localhost:8092
          predicates:
            - Path=/small/**
        - id: eventapp
          uri: http://localhost:8091
          predicates:
            - Path=/event/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/delta

server:
  port: 8093